server:
  port: 8081

springfox:
  documentation:
    auto-startup: false

spring:
  kafka:
    bootstrap-servers: ${DATA_SYNC_KAFKA_BROKER_URL:localhost:9092}
    listener:
      concurrency: ${CHARGES_DELTA_LISTENER_CONCURRENCY:1}

charges:
  delta:
    group-id: ${CHARGES_DELTA_GROUP_ID:charges-delta-consumer}
    topic: ${CHARGES_DELTA_TOPIC:charges-delta}
    retry-attempts: ${CHARGES_DELTA_ATTEMPTS:4}
    backoff-delay: ${CHARGES_DELTA_BACKOFF_DELAY:100}

mapper:
  descriptive-mappings-enabled: ${DESCRIPTIVE_MAPPINGS_ENABLED:false}

logger:
  namespace: charges-delta-consumer

api:
  charges-data-api-key: ${CHARGES_DATA_API_KEY:localhost}
  api-url: ${API_URL:localhost}
  charge-id-salt: ${CHARGE_ID_SALT:test1}
  trans-id-salt: ${TRANS_ID_SALT:test2}

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      path-mapping:
        health: charges-delta-consumer/healthcheck
  endpoint:
    health:
      show-details: never
      enabled: true
