server:
  port: 8081

springfox:
  documentation:
    auto-startup: false

spring:
  kafka:
    bootstrap-servers: ${DATA_SYNC_KAFKA_BROKER_URL:localhost:9092}

charges:
  delta:
    group-id: charges-delta-consumer
    topic: charges-delta
    retry-attempts: 4
    backoff-delay: 100

logger:
  namespace: charges-delta-consumer

api:
  charges-data-api-key: ${CHARGES_DATA_API_KEY:localhost}
  api-url: ${API_URL:localhost}
  charge-id-salt: ${CHARGE_ID_SALT:test1}
  trans-id-salt: ${TRANS_ID_SALT:test2}
