server:
  port: 8082

springfox:
  documentation:
    auto-startup: false

spring:
  kafka:
    bootstrap-servers: ${DATA_SYNC_KAFKA_BROKER_URL:localhost:9092}
    listener:
      concurrency: 1

charges:
  delta:
    group-id: charges-delta-consumer
    topic: charges-delta
    retry-attempts: 4
    backoff-delay: 10

logger:
  namespace: charges-delta-consumer

api:
  charges-data-api-key: ${CHARGES_DATA_API_KEY:MGQ1MGNlYmFkYzkxZTM2MzlkNGVmMzg4ZjgxMmEz}
  api-url: ${API_URL:http://localhost:8888}
  charge-id-salt: ${CHARGE_ID_SALT:chargeId_salt}
  trans-id-salt: ${TRANS_ID_SALT:transId_salt}

wiremock:
  server:
    port: 8888
