server:
  port: 8081

springfox:
  documentation:
    auto-startup: false

spring:
  kafka:
    bootstrap-servers: ${DATA_SYNC_KAFKA_BROKER_URL:localhost:9092}

charges:
  delta:
    group-id: charges-delta-consumer
    topic: charges-delta
    retry-attempts: 4
    backoff-delay: 100

logger:
  namespace: charges-delta-consumer

api:
  charges-data-api-key: ${CHARGES_DATA_API_KEY:MGQ1MGNlYmFkYzkxZTM2MzlkNGVmMzg4ZjgxMmEz}
  api-url: ${API_URL:http://localhost:8888}
  charge-id-salt: ${CHARGE_ID_SALT:chargeId_salt}
  trans-id-salt: ${TRANS_ID_SALT:transId_salt}

wiremock:
  server:
    port: 8888

logging:
  level:
    uk.gov.companieshouse.logging: trace